### PR TITLE
simple check to see if git-annex is already installed

### PR DESCRIPTION
**Pull request by db48x**
should check version number as well?

### CODE REVIEW

**Comment by cancerAlot** [comment]
i think a simple `command -v "git-annex" >/dev/null 2>&1 || { echo >&2 "git-annex not installed"; exit 1; }` should work for checking whether git-annex is in $PATH or not.

**Comment by db48x** [comment]
That's true, but git-annex probably isn't installed, so we wouldn't want to bail entirely in that case.

Also, if it's available from the user's distro then it's probably an older version; installing a local copy is the right way to get it.

**Comment by db48x** [comment]
Note to self: do version checking using the code from PR #5

**Comment by joeyh** [comment]
install-git-annex seems to deal with this well enough now

**Pull request closed without merging**
