### PR TITLE
install the right arch of git-annex

### PR DESCRIPTION
**Pull request by cancerAlot**

### CODE REVIEW

**Comment by joeyh** [comment]
i386 should work on amd64 systems as well. This might be on a removable drive etc, so keeping it portable seems like a win.

**Comment by cancerAlot** [comment]
is the i386-version working on ARM (f.e raspberry pi)?

**Comment by joeyh** [comment]
Arch detection is needed for arm. (The arm build will work on many arm subarchitectures.)

Also, OS detection is needed for OSX.

**Comment by cancerAlot** [comment]
uname -m gives "armv6l" or "armv7l" depending on the arm-version
and OSX should support i386; so i386-default should be right

**Pull request closed without merging**
