### PR TITLE
Use system git-annex copy if available

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by db48x** [comment]
The problem with using the system git annex is that it may not be sufficiently up to date. I don't happen to know off-hand the minimum required version, either.

**Comment by kyrias** [comment]
Could just have the most recent version as a requirement then, but having it download another copy for no reason is sort of annoying from a purity point of view, and would also make it rather hard to package the scripts for distributions.

**Comment by textfiles** [comment]
This project has caused an enormous amount of changes in the program in
question. It makes sense for the time being just still download a second
version while this brings itself out.

**Comment by db48x** [comment]
Those changes have plateaued; there's no reason we can't use the git-annex version from ~9 months ago, if it's already installed.

**Comment by kyrias** [comment]
Updated to check if the git-annex version is newer than `5.20150916`, which was released 8 months ago, before downloading a prebuilt git-annex version.

**Comment by kyrias** [comment]
Ping?

**Comment by kyrias** [comment]
@db48x ?

**Comment by kyrias** [comment]
@db48x ping?

**Pull request closed without merging**
